- name: ping module
  hosts: frontend
  tasks: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      start: started